[2024-07-26T02:42:28.460+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_email_operator.5-Email manual__2024-07-26T02:42:10.999273+00:00 [queued]>
[2024-07-26T02:42:28.468+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_email_operator.5-Email manual__2024-07-26T02:42:10.999273+00:00 [queued]>
[2024-07-26T02:42:28.468+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-26T02:42:28.468+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-07-26T02:42:28.468+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-26T02:42:28.476+0000] {taskinstance.py:1300} INFO - Executing <Task(EmailOperator): 5-Email> on 2024-07-26 02:42:10.999273+00:00
[2024-07-26T02:42:28.479+0000] {standard_task_runner.py:55} INFO - Started process 118 to run task
[2024-07-26T02:42:28.482+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_email_operator', '5-Email', 'manual__2024-07-26T02:42:10.999273+00:00', '--job-id', '1488', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_email_operator.py', '--cfg-path', '/tmp/tmpgj_n8n29']
[2024-07-26T02:42:28.483+0000] {standard_task_runner.py:83} INFO - Job 1488: Subtask 5-Email
[2024-07-26T02:42:28.523+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_email_operator.5-Email manual__2024-07-26T02:42:10.999273+00:00 [running]> on host 4e9420b3fb00
[2024-07-26T02:42:28.572+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caue.ausec@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_email_operator
AIRFLOW_CTX_TASK_ID=5-Email
AIRFLOW_CTX_EXECUTION_DATE=2024-07-26T02:42:10.999273+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-26T02:42:10.999273+00:00
[2024-07-26T02:42:28.580+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-26T02:42:28.580+0000] {configuration.py:663} WARNING - section/key [smtp/smtp_user] not found in config
[2024-07-26T02:42:28.580+0000] {email.py:268} INFO - Email alerting: attempt 1
[2024-07-26T02:42:28.581+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-07-26T02:42:28.588+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=exemplo_email_operator, task_id=5-Email, execution_date=20240726T024210, start_date=20240726T024228, end_date=20240726T024228
[2024-07-26T02:42:28.597+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1488 for task 5-Email ([Errno 111] Connection refused; 118)
[2024-07-26T02:42:28.624+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-26T02:42:28.635+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
