[2024-07-23T03:19:14.672+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_triggerule_allfailed.tsk2 manual__2024-07-23T03:19:14.281199+00:00 [queued]>
[2024-07-23T03:19:14.680+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_triggerule_allfailed.tsk2 manual__2024-07-23T03:19:14.281199+00:00 [queued]>
[2024-07-23T03:19:14.681+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T03:19:14.682+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-23T03:19:14.683+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T03:19:14.695+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk2> on 2024-07-23 03:19:14.281199+00:00
[2024-07-23T03:19:14.698+0000] {standard_task_runner.py:55} INFO - Started process 6453 to run task
[2024-07-23T03:19:14.701+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_triggerule_allfailed', 'tsk2', 'manual__2024-07-23T03:19:14.281199+00:00', '--job-id', '1305', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_triggerule_allfailed.py', '--cfg-path', '/tmp/tmpc01itzt_']
[2024-07-23T03:19:14.706+0000] {standard_task_runner.py:83} INFO - Job 1305: Subtask tsk2
[2024-07-23T03:19:14.760+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_triggerule_allfailed.tsk2 manual__2024-07-23T03:19:14.281199+00:00 [running]> on host 448a9c84d52e
[2024-07-23T03:19:14.802+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_triggerule_allfailed
AIRFLOW_CTX_TASK_ID=tsk2
AIRFLOW_CTX_EXECUTION_DATE=2024-07-23T03:19:14.281199+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-23T03:19:14.281199+00:00
[2024-07-23T03:19:14.803+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-23T03:19:14.804+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 4']
[2024-07-23T03:19:14.809+0000] {subprocess.py:86} INFO - Output:
[2024-07-23T03:19:14.811+0000] {subprocess.py:97} INFO - Command exited with return code 4
[2024-07-23T03:19:14.818+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 4.
[2024-07-23T03:19:14.821+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=exemplo_triggerule_allfailed, task_id=tsk2, execution_date=20240723T031914, start_date=20240723T031914, end_date=20240723T031914
[2024-07-23T03:19:14.829+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1305 for task tsk2 (Bash command failed. The command returned a non-zero exit code 4.; 6453)
[2024-07-23T03:19:14.844+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-23T03:19:14.858+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
