[2024-07-27T19:35:42.463+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_dataset_producer.tsk1 manual__2024-07-27T19:35:41.132629+00:00 [queued]>
[2024-07-27T19:35:42.473+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_dataset_producer.tsk1 manual__2024-07-27T19:35:41.132629+00:00 [queued]>
[2024-07-27T19:35:42.474+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-27T19:35:42.474+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-27T19:35:42.474+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-27T19:35:42.486+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): tsk1> on 2024-07-27 19:35:41.132629+00:00
[2024-07-27T19:35:42.491+0000] {standard_task_runner.py:55} INFO - Started process 27577 to run task
[2024-07-27T19:35:42.493+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_dataset_producer', 'tsk1', 'manual__2024-07-27T19:35:41.132629+00:00', '--job-id', '1836', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_dataset_producer.py', '--cfg-path', '/tmp/tmpnyb95mxa']
[2024-07-27T19:35:42.495+0000] {standard_task_runner.py:83} INFO - Job 1836: Subtask tsk1
[2024-07-27T19:35:42.595+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_dataset_producer.tsk1 manual__2024-07-27T19:35:41.132629+00:00 [running]> on host ec0bbc56d6ed
[2024-07-27T19:35:42.674+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_dataset_producer
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-07-27T19:35:41.132629+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-27T19:35:41.132629+00:00
[2024-07-27T19:35:42.677+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exemplo_dataset_producer.py", line 20, in duplicate_file
    dataset = pd.read_csv('/opt/airflow/Churn.csv',sep=";")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/Churn.csv'
[2024-07-27T19:35:42.689+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=exemplo_dataset_producer, task_id=tsk1, execution_date=20240727T193541, start_date=20240727T193542, end_date=20240727T193542
[2024-07-27T19:35:42.699+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1836 for task tsk1 ([Errno 2] No such file or directory: '/opt/airflow/Churn.csv'; 27577)
[2024-07-27T19:35:42.718+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-27T19:35:42.731+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
