[2024-07-25T02:16:18.885+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_triggerule_allfailed.tsk2 manual__2024-07-25T02:16:16.826014+00:00 [queued]>
[2024-07-25T02:16:18.914+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_triggerule_allfailed.tsk2 manual__2024-07-25T02:16:16.826014+00:00 [queued]>
[2024-07-25T02:16:18.915+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-25T02:16:18.916+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-25T02:16:18.920+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-25T02:16:18.979+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk2> on 2024-07-25 02:16:16.826014+00:00
[2024-07-25T02:16:18.986+0000] {standard_task_runner.py:55} INFO - Started process 31158 to run task
[2024-07-25T02:16:18.993+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_triggerule_allfailed', 'tsk2', 'manual__2024-07-25T02:16:16.826014+00:00', '--job-id', '1374', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_triggerule_allfailed.py', '--cfg-path', '/tmp/tmpz9x99n33']
[2024-07-25T02:16:19.005+0000] {standard_task_runner.py:83} INFO - Job 1374: Subtask tsk2
[2024-07-25T02:16:19.123+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_triggerule_allfailed.tsk2 manual__2024-07-25T02:16:16.826014+00:00 [running]> on host 448a9c84d52e
[2024-07-25T02:16:19.185+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_triggerule_allfailed
AIRFLOW_CTX_TASK_ID=tsk2
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T02:16:16.826014+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-25T02:16:16.826014+00:00
[2024-07-25T02:16:19.187+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-25T02:16:19.188+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 4']
[2024-07-25T02:16:19.208+0000] {subprocess.py:86} INFO - Output:
[2024-07-25T02:16:19.211+0000] {subprocess.py:97} INFO - Command exited with return code 4
[2024-07-25T02:16:19.228+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 4.
[2024-07-25T02:16:19.235+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=exemplo_triggerule_allfailed, task_id=tsk2, execution_date=20240725T021616, start_date=20240725T021618, end_date=20240725T021619
[2024-07-25T02:16:19.246+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1374 for task tsk2 (Bash command failed. The command returned a non-zero exit code 4.; 31158)
[2024-07-25T02:16:19.281+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-25T02:16:19.297+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
